kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: refresh-connection-es-to-vault
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["external-secrets.io"]
  resources: ["*"]
  verbs: ["*"]