apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: refresh-connection-es-to-vault
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: refresh-connection-es-to-vault
  namespace: {{ .Values.cronjobs.refreshConnectionEsToVault.namespace }}